
import java.sql.*;
import java.text.SimpleDateFormat;
//import java.text.*;
import javax.swing.*;
import java.util.Date;
import java.util.Calendar;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author priya
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ta = new javax.swing.JTextField();
        c1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        c2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        td = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        t5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 473));
        setSize(new java.awt.Dimension(700, 470));
        getContentPane().setLayout(null);
        getContentPane().add(t2);
        t2.setBounds(170, 90, 120, 30);
        getContentPane().add(t3);
        t3.setBounds(170, 130, 120, 30);
        getContentPane().add(t4);
        t4.setBounds(170, 210, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Age");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 214, 40, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Arrival");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 250, 60, 30);
        getContentPane().add(ta);
        ta.setBounds(170, 250, 120, 30);

        c1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c1.setText("Male");
        c1.setOpaque(false);
        getContentPane().add(c1);
        c1.setBounds(170, 170, 60, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Departure");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 300, 70, 20);

        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        getContentPane().add(t9);
        t9.setBounds(450, 170, 90, 30);

        c2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c2.setText("Female");
        c2.setOpaque(false);
        getContentPane().add(c2);
        c2.setBounds(220, 170, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Advance");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 340, 50, 14);
        getContentPane().add(t1);
        t1.setBounds(170, 50, 120, 30);
        getContentPane().add(td);
        td.setBounds(170, 290, 120, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel2.setText("Room No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 50, 80, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Booking No");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(360, 170, 70, 30);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 240, 70, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText(" Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 90, 60, 30);
        getContentPane().add(t7);
        t7.setBounds(170, 330, 120, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 130, 60, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Sex");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 180, 40, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Charges");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 374, 60, 20);
        getContentPane().add(t8);
        t8.setBounds(170, 370, 120, 30);

        jButton2.setText("MAIN MENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 240, 140, 30);
        getContentPane().add(t5);
        t5.setBounds(170, 410, 120, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("BOOKING COUNTER");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(250, 10, 250, 30);

        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 290, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Time Spent");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 420, 70, 10);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("dd-mm-yyyy");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(290, 270, 80, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/10158_Maritimo-Hotel-Reception-Lobby.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setPreferredSize(new java.awt.Dimension(700, 470));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 700, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        String r=t1.getText();
        String n=t2.getText();
        String ad=t3.getText();
        String s="";
        if(c1.isSelected())
        s="M";
        else
        {
        if (c2.isSelected())
        s="F";
        else 
            JOptionPane.showMessageDialog(null,"Please select Sex");
        }
        int ag=Integer.parseInt(t4.getText());
       
        String adts=ta.getText();
        SimpleDateFormat df=new SimpleDateFormat("dd-mm-yyyy");
        
        Date adt=new Date();
        try
        {
            adt=df.parse(adts);
        }
       catch(Exception e)
       {
       JOptionPane.showMessageDialog(null,e.getMessage());
       }
      Date dt=Calendar.getInstance().getTime();
      long diff=dt.getTime()-adt.getTime();
      long days=diff/(1000L*60L*60L*24L);
     t5.setText(""+days);
        td.setText(""+dt);
         
        
        double am=Double.parseDouble(t7.getText());
        double c=Double.parseDouble(t8.getText());
        
        try
        {
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/Booking","root","akarsh");
        Statement st=(Statement) con.createStatement();
        int b=100;
       
       t9.setText(""+b);
        st.executeUpdate("Insert into Booking values('"+b+"','"+r+"','"+n+"','"+ad+"','"+s+"','"+ag+"','"+am+"','"+c+"','"+adts+"','"+dt+"','"+days+"')");
        con.close();
        st.close();
        }
         catch(Exception e)
        {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        MainPage ob=new MainPage();
     ob.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
     
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTextField ta;
    private javax.swing.JTextField td;
    // End of variables declaration//GEN-END:variables
}
